export const departmentList = [
	'Ahuachapán',
	'Cabañas',
	'Chalatenango',
	'Cuscatlán',
	'La Libertad',
	'La Paz',
	'La Unión',
	'Morazán',
	'San Miguel',
	'San Salvador',
	'San Vicente',
	'Santa Ana',
	'Sonsonate',
	'Usulután',
];

export const keyList = {
	transmittance: 'transmittance',
	window: 'window',
	packageConfiguration: 'package-configuration',
	package: 'package',
	proportion: 'proportion',
	shading: 'shading',
	roofs: 'roofs',
};

export const codePackagePrefix = 'PACK';
export const ProjectStatus = {
	inProgress: 0,
	inRevision: 1,
	accepted: 2,
	denied: 3,
};

export const RoleNames = {
	Operator: 'Operador',
	Admin: 'Administrador',
	SuperAdmin: 'SuperAdministrador',
};
export const DepartmentsWithProvincies = [
	{
		department: 'Ahuachapán',
		code: 'AHUA',
		municipality: [
			'Ahuachapán',
			'Apaneca',
			'Atiquizaya',
			'Concepción de Ataco',
			'El Refugio',
			'Guaymango',
			'Jujutla',
			'San Francisco Menéndez',
			'San Lorenzo',
			'San Pedro Puxtla',
			'Tacuba',
			'Turín',
		],
		id: 0,
	},
	{
		department: 'Cabañas',
		code: 'CAB',
		municipality: [
			'Cinquera',
			'Dolores',
			'Guacotecti',
			'Ilobasco',
			'Jutiapa',
			'San Isidro',
			'Sensuntepeque',
			'Tejutepeque',
			'Victoria',
		],
		id: 1,
	},
	{
		department: 'Chalatenango',
		code: 'CHAL',
		municipality: [
			'Agua Caliente',
			'Arcatao',
			'Azacualpa',
			'Chalatenango',
			'Citalá',
			'Comalapa',
			'Concepción Quezaltepeque',
			'Dulce Nombre de María',
			'El Carrizal',
			'El Paraíso',
			'La Laguna',
			'La Palma',
			'La Reina',
			'Las Vueltas',
			'Nombre de Jesús',
			'Nueva Concepción',
			'Nueva Trinidad',
			'Ojos de Agua',
			'Potonico',
			'San Antonio de la Cruz',
			'San Antonio Los Ranchos',
			'San Fernando',
			'San Francisco Lempa',
			'San Francisco Morazán',
			'San Ignacio',
			'San Isidro Labrador',
			'San José Cancasque',
			'San José Las Flores',
			'San Luis del Carmen',
			'San Miguel de Mercedes',
			'San Rafael',
			'Santa Rita',
			'Tejutla',
		],
		id: 2,
	},
	{
		department: 'Cuscatlán',
		code: 'CUS',
		municipality: [
			'Candelaria',
			'Cojutepeque',
			'El Carmen',
			'El Rosario',
			'Monte San Juan',
			'Oratorio de Concepción',
			'San Bartolomé Perulapía',
			'San Cristóbal',
			'San José Guayabal',
			'San Pedro Perulapán',
			'San Rafael Cedros',
			'San Ramón',
			'Santa Cruz Analquito',
			'Santa Cruz Michapa',
			'Suchitoto',
			'Tenancingo',
		],
		id: 3,
	},
	{
		department: 'La Libertad',
		code: 'LIB',
		municipality: [
			'Antiguo Cuscatlán',
			'Chiltiupán',
			'Ciudad Arce',
			'Colón',
			'Comasagua',
			'Huizúcar',
			'Jayaque',
			'Jicalapa',
			'La Libertad',
			'Nueva San Salvador',
			'Nuevo Cuscatlán',
			'Quezaltepeque',
			'San Juan Opico',
			'San Matías',
			'San Pablo Tacachico',
			'Santa Tecla',
			'Talnique',
			'Tamanique',
			'Teotepeque',
			'Tepecoyo',
			'Zaragoza',
		],
		id: 4,
	},
	{
		department: 'La Paz',
		code: 'PAZ',
		municipality: [
			'Cuyultitán',
			'El Rosario',
			'Jerusalén',
			'Mercedes La Ceiba',
			'Olocuilta',
			'Paraíso de Osorio',
			'San Antonio Masahuat',
			'San Emigdio',
			'San Francisco Chinameca',
			'San Juan Nonualco',
			'San Juan Talpa',
			'San Juan Tepezontes',
			'San Luis La Herradura',
			'San Luis Talpa',
			'San Miguel Tepezontes',
			'San Pedro Masahuat',
			'San Pedro Nonualco',
			'San Rafael Obrajuelo',
			'Santa María Ostuma',
			'Santiago Nonualco',
			'Tapalhuaca',
			'Zacatecoluca',
		],
		id: 5,
	},
	{
		department: 'La Unión',
		code: 'UNIO',
		municipality: [
			'Anamorós',
			'Bolívar',
			'Concepción de Oriente',
			'Conchagua',
			'El Carmen',
			'El Sauce',
			'Intipucá',
			'La Unión',
			'Lislique',
			'Meanguera del Golfo',
			'Nueva Esparta',
			'Pasaquina',
			'Polorós',
			'San Alejo',
			'San José',
			'Santa Rosa de Lima',
			'Yayantique',
			'Yucuaiquín',
		],
		id: 6,
	},
	{
		department: 'Morazán',
		code: 'MOR',
		municipality: [
			'Arambala',
			'Cacaopera',
			'Chilanga',
			'Corinto',
			'Delicias de Concepción',
			'El Divisadero',
			'El Rosario',
			'Gualococti',
			'Guatajiagua',
			'Joateca',
			'Jocoaitique',
			'Jocoro',
			'Lolotiquillo',
			'Meanguera',
			'Osicala',
			'Perquín',
			'San Carlos',
			'San Fernando',
			'San Francisco Gotera',
			'San Isidro',
			'San Simón',
			'Sensembra',
			'Sociedad',
			'Torola',
			'Yamabal',
			'Yoloaiquín',
		],
		id: 7,
	},
	{
		department: 'San Miguel',
		code: 'MIG',
		municipality: [
			'Carolina',
			'Chapeltique',
			'Chinameca',
			'Chirilagua',
			'Ciudad Barrios',
			'Comacarán',
			'El Tránsito',
			'Lolotique',
			'Moncagua',
			'Nueva Guadalupe',
			'Nuevo Edén de San Juan',
			'Quelepa',
			'San Antonio del Mosco',
			'San Gerardo',
			'San Jorge',
			'San Luis de la Reina',
			'San Miguel',
			'San Rafael Oriente',
			'Sesori',
			'Uluazapa',
		],
		id: 8,
	},
	{
		department: 'San Salvador',
		code: 'SAL',
		municipality: [
			'Aguilares',
			'Apopa',
			'Ayutuxtepeque',
			'Cuscatancingo',
			'Delgado',
			'El Paisnal',
			'Guazapa',
			'Ilopango',
			'Mejicanos',
			'Nejapa',
			'Panchimalco',
			'Rosario de Mora',
			'San Marcos',
			'San Martín',
			'San Salvador',
			'Santiago Texacuangos',
			'Santo Tomás',
			'Soyapango',
			'Tonacatepeque',
		],
		id: 9,
	},
	{
		department: 'San Vicente',
		code: 'VIC',
		municipality: [
			'Apastepeque',
			'Guadalupe',
			'San Cayetano Istepeque',
			'San Esteban Catarina',
			'San Ildefonso',
			'San Lorenzo',
			'San Sebastián',
			'San Vicente',
			'Santa Clara',
			'Santo Domingo',
			'Tecoluca',
			'Verapaz',
		],
		id: 10,
	},
	{
		department: 'Santa Ana',
		code: 'ANA',
		municipality: [
			'Candelaria de la Frontera',
			'Chalchuapa',
			'Coatepeque',
			'El Congo',
			'El Porvenir',
			'Masahuat',
			'Metapán',
			'San Antonio Pajonal',
			'San Sebastián Salitrillo',
			'Santa Ana',
			'Santa Rosa Guachipilín',
			'Santiago de la Frontera',
			'Texistepeque',
		],
		id: 11,
	},
	{
		department: 'Sonsonate',
		code: 'SON',
		municipality: [
			'Acajutla',
			'Armenia',
			'Caluco',
			'Cuisnahuat',
			'Izalco',
			'Juayúa',
			'Nahuizalco',
			'Nahulingo',
			'Salcoatitán',
			'San Antonio del Monte',
			'San Julián',
			'Santa Catarina Masahuat',
			'Santa Isabel Ishuatán',
			'Santo Domingo de Guzmán',
			'Sonsonate',
			'Sonzacate',
		],
		id: 12,
	},
	{
		department: 'Usulután',
		code: 'USU',
		municipality: [
			'Alegría',
			'Berlín',
			'California',
			'Concepción Batres',
			'El Triunfo',
			'Ereguayquín',
			'Estanzuelas',
			'Jiquilisco',
			'Jucuapa',
			'Jucuarán',
			'Mercedes Umaña',
			'Nueva Granada',
			'Ozatlán',
			'Puerto El Triunfo',
			'San Agustín',
			'San Buenaventura',
			'San Dionisio',
			'San Francisco Javier',
			'Santa Elena',
			'Santa María',
			'Santiago de María',
			'Tecapán',
			'Usulután',
		],
		id: 13,
	},
];
