export const departmentList = [
	'',
	'Ahuachapán',
	'Cabañas',
	'Chalatenango',
	'Cuscatlán',
	'La Libertad',
	'La Paz',
	'La Unión',
	'Morazán',
	'San Miguel',
	'San Salvador',
	'San Vicente',
	'Santa Ana',
	'Sonsonate',
	'Usulután',
];

export const municipalityList = [
	'',
	'Ahuachapán',
	'Apaneca',
	'Atiquizaya',
	'Concepción de Ataco',
	'El Refugio',
	'Guaymango',
	'Jujutla',
	'San Francisco Menéndez',
	'San Lorenzo',
	'San Pedro Puxtla',
	'Tacuba',
	'Turín',
	'Candelaria de la Frontera',
	'Chalchuapa',
	'Coatepeque',
	'El Congo',
	'El Porvenir',
	'Masahuat',
	'Metapán',
	'San Antonio Pajonal',
	'San Sebastián Salitrillo',
	'Santa Ana',
	'Santa Rosa Guachipilín',
	'Santiago de la Frontera',
	'Texistepeque',
	'Acajutla',
	'Armenia',
	'Caluco',
	'Cuisnahuat',
	'Izalco',
	'Juayúa',
	'Nahuizalco',
	'Nahulingo',
	'Salcoatitán',
	'San Antonio del Monte',
	'San Julián',
	'Santa Catarina Masahuat',
	'Santa Isabel Ishuatán',
	'Santo Domingo Guzmán',
	'Sonsonate',
	'Sonzacate',
	'Agua Caliente',
	'Arcatao',
	'Azacualpa',
	'Chalatenango',
	'Comalapa',
	'Citalá',
	'Concepción Quezaltepeque',
	'Dulce Nombre de María',
	'El Carrizal',
	'El Paraíso',
	'La Laguna',
	'La Palma',
	'La Reina',
	'Las Vueltas',
	'Nueva Concepción',
	'Nueva Trinidad',
	'Nombre de Jesús',
	'Ojos de Agua',
	'Potonico',
	'San Antonio de la Cruz',
	'San Antonio Los Ranchos',
	'San Fernando',
	'San Francisco Lempa',
	'San Francisco Morazán',
	'San Ignacio',
	'San Isidro Labrador',
	'San José Cancasque',
	'San José Las Flores',
	'San Luis del Carmen',
	'San Miguel de Mercedes',
	'San Rafael',
	'Santa Rita',
	'Tejutla',
	'Candelaria',
	'Cojutepeque',
	'El Carmen',
	'El Rosario',
	'Monte San Juan',
	'Oratorio de Concepción',
	'San Bartolomé Perulapía',
	'San Cristóbal',
	'San José Guayabal',
	'San Pedro Perulapán',
	'San Rafael Cedros',
	'San Ramón',
	'Santa Cruz Analquito',
	'Santa Cruz Michapa',
	'Suchitoto',
	'Tenancingo',
	'Aguilares',
	'Apopa',
	'Ayutuxtepeque',
	'Cuscatancingo',
	'Ciudad Delgado',
	'El Paisnal',
	'Guazapa',
	'Ilopango',
	'Mejicanos',
	'Nejapa',
	'Panchimalco',
	'Rosario de Mora',
	'San Marcos',
	'San Martín',
	'San Salvador',
	'Santiago Texacuangos',
	'Santo Tomás',
	'Soyapango',
	'Tonacatepeque',
	'Antiguo Cuscatlán',
	'Chiltiupán',
	'Ciudad Arce',
	'Colón',
	'Comasagua',
	'Huizúcar',
	'Jayaque',
	'Jicalapa',
	'La Libertad',
	'Santa Tecla',
	'Nuevo Cuscatlán',
	'San Juan Opico',
	'Quezaltepeque',
	'Sacacoyo',
	'San José Villanueva',
	'San Matías',
	'San Pablo Tacachico',
	'Talnique',
	'Tamanique',
	'Teotepeque',
	'Tepecoyo',
	'Zaragoza',
	'Apastepeque',
	'Guadalupe',
	'San Cayetano Istepeque',
	'San Esteban Catarina',
	'San Ildefonso',
	'San Lorenzo',
	'San Sebastián',
	'San Vicente',
	'Santa Clara',
	'Santo Domingo',
	'Tecoluca',
	'Tepetitán',
	'Verapaz',
	'Cinquera',
	'Dolores',
	'Guacotecti',
	'Ilobasco',
	'Jutiapa',
	'San Isidro',
	'Sensuntepeque',
	'Tejutepeque',
	'Victoria',
	'Cuyultitán',
	'El Rosario',
	'Jerusalén',
	'Mercedes La Ceiba',
	'Olocuilta',
	'Paraíso de Osorio',
	'San Antonio Masahuat',
	'San Emigdio',
	'San Francisco Chinameca',
	'San Juan Nonualco',
	'San Juan Talpa',
	'San Juan Tepezontes',
	'San Luis Talpa',
	'San Luis La Herradura',
	'San Miguel Tepezontes',
	'San Pedro Masahuat',
	'San Pedro Nonualco',
	'San Rafael Obrajuelo',
	'Santa María Ostuma',
	'Santiago Nonualco',
	'Tapalhuaca',
	'Zacatecoluca',
	'Alegría',
	'Berlín',
	'California',
	'Concepción Batres',
	'El Triunfo',
	'Ereguayquín',
	'Estanzuelas',
	'Jiquilisco',
	'Jucuapa',
	'Jucuarán',
	'Mercedes Umaña',
	'Nueva Granada',
	'Ozatlán',
	'Puerto El Triunfo',
	'San Agustín',
	'San Buenaventura',
	'San Dionisio',
	'San Francisco Javier',
	'Santa Elena',
	'Santa María',
	'Santiago de María',
	'Tecapán',
	'Usulután',
	'Carolina',
	'Chapeltique',
	'Chinameca',
	'Chirilagua',
	'Ciudad Barrios',
	'Comacarán',
	'El Tránsito',
	'Lolotique',
	'Moncagua',
	'Nueva Guadalupe',
	'Nuevo Edén de San Juan',
	'Quelepa',
	'San Antonio del Mosco',
	'San Gerardo',
	'San Jorge',
	'San Luis de la Reina',
	'San Miguel',
	'San Rafael Oriente',
	'Sesori',
	'Uluazapa',
	'Arambala',
	'Cacaopera',
	'Chilanga',
	'Corinto',
	'Delicias de Concepción',
	'El Divisadero',
	'El Rosario',
	'Gualococti',
	'Guatajiagua',
	'Joateca',
	'Jocoaitique',
	'Jocoro',
	'Lolotiquillo',
	'Meanguera',
	'Osicala',
	'Perquín',
	'San Carlos',
	'San Fernando',
	'San Francisco Gotera',
	'San Isidro',
	'San Simón',
	'Sensembra',
	'Sociedad',
	'Torola',
	'Yamabal',
	'Yoloaiquín',
	'Anamorós',
	'Bolívar',
	'Concepción de Oriente',
	'Conchagua',
	'El Carmen',
	'El Sauce',
	'Intipucá',
	'La Unión',
	'Lislique',
	'Meanguera del Golfo',
	'Nueva Esparta',
	'Pasaquina',
	'Polorós',
	'San Alejo',
	'San José',
	'Santa Rosa de Lima',
	'Yayantique',
	'Yucuaiquín',
];

export const keyList = {
	transmittance: 'transmittance',
	window: 'window',
	packageConfiguration: 'package-configuration',
	package: 'package',
	proportion: 'proportion',
	shading: 'shading',
	roofs: 'roofs',
};

export const codePackagePrefix = 'PACK';
export const ProjectStatus = {
	inProgress: 0,
	inRevision: 1,
	accepted: 2,
	denied: 3,
};
